# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'elasticsearch-persistence', '= 7.0.0.pre'
gem 'sidekiq'
gem 'redis'
